name: malina
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^14.2.0
  qr_code_scanner: ^1.0.1
  get_it: ^7.7.0
  injectable: ^2.4.1
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  flutter_svg: ^2.0.10+1
  expandable_page_view: ^1.0.17
  talker_flutter: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  flutter_gen_runner:
  go_router_builder: ^2.5.1
  injectable_generator: ^2.6.1
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
